language: cpp
install:
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
  - tar -xzvf cmake-3.0.2.tar.gz 
  - cd cmake-3.0.2.tar.gz
  - ./configure && make && make install
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-0
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y swig
  - sudo apt-get install -y libgtest-dev
before_script: 
  - mkdir cmake && cd cmake
  - cmake ..
script: "make"
compiler:
  - clang
  - gcc